const projects = [
    {
        name: "My Grade Book",
        github: "https://github.com/danmorales209/project-ld3",
        deployed: "https://pacific-taiga-52007.herokuapp.com/teacher",
        image: "./images/myGradeBook.png",
        description: "An app for teaches to create assignments and post grades.",
    },
    {
        name: "Hangman Game",
        github: "https://github.com/thedanielenrico/Word-Guess-Game",
        deployed: 'https://thedanielenrico.github.io/Word-Guess-Game/',
        image: "./images/hangman.png",
        description: "A random letter is picked and the user has to make a guess.",  
    },
    {
        name: "Friend Finder",
        github: "https://github.com/thedanielenrico/FriendFinder",
        deployed: "https://boiling-temple-84585.herokuapp.com/",
        image: "./images/friendFinder1.png",
        description: "A quick survey to find a compatiable friend.",
    },
    {
        name: "Stone Collecter Game",
        github: "https://github.com/thedanielenrico/unit-4-game",
        deployed: "https://thedanielenrico.github.io/unit-4-game/",
        image: "./images/gemstone.png",
        description: "Click stones that have random values to reach a given number.",
    },
    {
        name: "Make It MES Software",
        github: "https://github.com/thedanielenrico/project-cool-mes",
        deployed: "https://enigmatic-plains-72936.herokuapp.com/",
        image: "./images/makeIt.png",
        description: "A Manufacturing Execution System for small businesses.",
    },
    {
        name: "Science Trivia",
        github: "https://github.com/thedanielenrico/TriviaGame",
        deployed: "https://thedanielenrico.github.io/TriviaGame/",
        image: "./images/trivia.png",
        description: "A timed and themed trivia game.",
    },
    {
        name: "Giftastic",
        github: "https://github.com/thedanielenrico/GifTastic",
        deployed: "https://thedanielenrico.github.io/GifTastic/",
        image: "./images/giphy.png",
        description: "Search for your favorite GIF's or click the buttons if you can't decide.",
    },
    {
        name: "Train Scheduler",
        github: "https://github.com/thedanielenrico/TrainTime",
        deployed: "https://thedanielenrico.github.io/TrainTime/",
        image: "./images/train.png",
        description: "Keep track of train times and destinations and add new ones as well.",
    },
    {
        name: "Eat-da-burger",
        github: "https://github.com/thedanielenrico/burger",
        deployed: "https://desolate-fortress-38406.herokuapp.com/",
        image: "./images/burger.png",
        description: "A simple burger ordering app that allows to devour them too.",
    },
    {
        name: "Clicky Game",
        github: "https://github.com/thedanielenrico/clickyGame",
        deployed: "https://rocky-beyond-25168.herokuapp.com/",
        image: "./images/clickygame.png",
        description: "Click the diffferent characters to reach a highscore.",
    },
    {
        name: "All The News",
        github: "https://github.com/thedanielenrico/newsScraper",
        deployed: "https://hidden-crag-77899.herokuapp.com/",
        image: "./images/newsSCraper.png",
        description: "Find and save news articles that interest you.",
    },
]

export default projects;